version: '3'

networks:
  redelab:
    ipam:
      driver: default

services:
  pm2-node-app:
    container_name: pm2NodeApp
    build: .
    image: node-app-img:1.0
    ports:
      - "4200:4200"
    networks:
       redelab:
